/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as TestsTestCaseIdImport } from './routes/tests.$testCaseId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TestsTestCaseIdRoute = TestsTestCaseIdImport.update({
  id: '/tests/$testCaseId',
  path: '/tests/$testCaseId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/tests/$testCaseId': {
      id: '/tests/$testCaseId'
      path: '/tests/$testCaseId'
      fullPath: '/tests/$testCaseId'
      preLoaderRoute: typeof TestsTestCaseIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tests/$testCaseId': typeof TestsTestCaseIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tests/$testCaseId': typeof TestsTestCaseIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/tests/$testCaseId': typeof TestsTestCaseIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/tests/$testCaseId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/tests/$testCaseId'
  id: '__root__' | '/' | '/tests/$testCaseId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TestsTestCaseIdRoute: typeof TestsTestCaseIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TestsTestCaseIdRoute: TestsTestCaseIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/tests/$testCaseId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/tests/$testCaseId": {
      "filePath": "tests.$testCaseId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
