/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TestCaseIdImport } from './routes/$testCaseId'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const TestCaseIdRoute = TestCaseIdImport.update({
  id: '/$testCaseId',
  path: '/$testCaseId',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$testCaseId': {
      id: '/$testCaseId'
      path: '/$testCaseId'
      fullPath: '/$testCaseId'
      preLoaderRoute: typeof TestCaseIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$testCaseId': typeof TestCaseIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$testCaseId': typeof TestCaseIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/$testCaseId': typeof TestCaseIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$testCaseId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$testCaseId'
  id: '__root__' | '/' | '/$testCaseId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TestCaseIdRoute: typeof TestCaseIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TestCaseIdRoute: TestCaseIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$testCaseId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$testCaseId": {
      "filePath": "$testCaseId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
